// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ciooutoeeiknfnlmwkvn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNpb291dG9lZWlrbmZubG13a3ZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzMzM3MTIsImV4cCI6MjA2NjkwOTcxMn0.VWtvN_0xSlUP0I1Pf1DKhwSECvURzfo2Jq3jX8YYezA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});